import type { Metadata } from "next";
import { Navbar, WhatsUpButton } from "../features";

import { ToastContainer } from "react-toastify";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <Navbar />
        <WhatsUpButton />
        <ToastContainer style={{ fontSize: "1rem" }} />

        {children}
      </body>
    </html>
  );
}
